import "oaidl.idl";
import "ocidl.idl";

// File Example1.idl
[
    // A unique identifier that distinguishes this
    // interface from other interfaces.
    uuid(e2c5e2dc-3932-4d23-bd94-e57af389cbf1), //my uuid

    /*uuid(00000001-EAF3-4A7A-A0F2-BCE4C30DA77E)*/ //Example uuid

    // This is version 1.0 of this interface.
    version(1.0),

    // This interface will use an implicit binding
    // handle named hExample1Binding.
    implicit_handle(handle_t hExample1Binding)
]
interface Example1 // The interface is named Example1
{
    // A function that takes a zero-terminated string.
    void Output(
        [in, string] const char* szOutput);


	const unsigned int cMaxBuf = 100000;

	int download_to_client(
		[string][in] const  char* path,
		[out] char buf[cMaxBuf],
		[out]  int* length_buf,
		[in] int index,
		[out] int* check_eof
	);
	int send_to_server(
		[string][in] const char* file_name,
		[in] char buf[cMaxBuf],
		[in] int length_buf,
		[in] int index,
		[in] int check_eof
	);

	int delete_file_on_server(
		[string][in] const char* path,
		[in] int index
	);

	int login_client(
		[string][in]  const char* login,
		[string][in]  const char* password,
		[out] int* index
	);

    int client_out(
        [in] int index
    );

}